### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by stefs** [rickykresslein/kreativ#1]
Hi, it would be great to see a screenshot of the app before downloading, on GitHub or the project website 😊

**Comment by rickykresslein** [comment]
Thanks for the suggestion! I've added a screenshot. Sorry it took me so long to get to it, I'm not really maintaining this app anymore. Most of the functionality has been replaced by my new app [Furtherance](https://github.com/lakoliu/Furtherance), which is a time tracking app as well.
